### ISSUE TITLE
Integration with anki flashcard

### ISSUE THREAD

**Issue by ropoko** [ropoko/cli-dictionary#2]
when searching for the word, allow the user to type a tag (example "--add"), and then that word and its meaning would be added to a text file.

Objective: When we are learning an word, it's common that we would "revisit" the meaning of that word many times until we decorate the meaning. Knowing this, it would be useful having a file to easily review the word.

**Comment by miguel-nascimento** [comment]
Another idea for this is using the history to produce a Anki Flashcard when the word is searched in the cli-dictonary.

Anki flashcards have the same concept of "revisit" the meaning of the word many times, using Anki to learn the word with time spaced repetition

**Comment by ropoko** [comment]
great idea, I will edit the title of this issue to this

**Comment by delsehi** [comment]
That would be genuinely useful to me. I often read books in foreign languages, look up new words in google translate and then manually add a new card. The problem is that even though I'm pretty fast, it's time consuming enough to bother my reading experience. 

### Some suggestions on requirements: 

* The user should be able to select the meaning they were looking for and only add that as a card, so it does not get bloated with corner cases. 
* The user should be able to confirm first that the generated card looks alright, so that the deck does not get filled up with crappy cards
* The user should be able to postpone the actual creation of the card as a draught, if it does not look like the program made it properly and they need to change something but still want the information saved somewhere. 
* The user should be able to change the text on the card manually 
* The user should be able to choose what kind of card it is (basic, basic and reversed)
* If the language has some API available to get example sentences containing the word, the user should be able to fetch one of those and create a cloze-card.

**Comment by ropoko** [comment]
I'm doing some improvements on branch dev as you can see on the "to-do list", maybe I won't be able to implement all your requests, but after this first release with anki integration, let's see how it works and then improve this integration. 

thanks for your comment :D

**Comment by ropoko** [comment]
### The new realese v2.3.3 is available with an integration with anki.

#### Features Added:
- Cloze Cards created with random examples of the word requested
- Adding the parameter `--card` you're able to create a card of type: basic, basic-reverse or cloze
- Creating cards for others profiles adding the parameter `--profile <name-profile>`

the cards types: basic and basic-reverse randomize a meaning to create the card
